version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social-media-portal
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Node environment
      - NODE_ENV=production
      
      # Database - PostgreSQL
      - DATABASE_URL=${DATABASE_URL}
      
      # Authentication - Keycloak SSO with NextAuth.js
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      
      # Public Environment Variables (for frontend)
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
      
      # Security
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      
      # Port
      - PORT=3000
      - HOSTNAME=0.0.0.0
      
    volumes:
      # Persist uploads directory
      - ./uploads:/app/uploads
      
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s